#!/usr/bin/env bash
set -euo pipefail
source "$(dirname "$0")/00_config.sh"

# =============================================================================
# Install fgbio and LoFreq into the ctdna2 conda environment.
#
# fgbio: Fulcrum Genomics toolkit for UMI/consensus calling (bioconda).
#   Installed as a conda package — provides both a wrapper script and a JAR.
#   The JAR path is written to scripts/fgbio_env.sh so that 14_align_arms_cd.sh
#   can source it and invoke fgbio directly via `java -jar $FGBIO_JAR`.
#   Wrapper scripts suppress JVM memory flags, so we prefer the JAR directly.
#
# LoFreq: Low-frequency variant caller using Poisson model (bioconda).
#   Particularly sensitive at low VAF because it explicitly models per-base
#   error rates from quality scores — more principled than Mutect2 at VAF < 1%.
#   Used in Arm A and Arm C for tumor-only calling.
#
# This script is idempotent: each tool is checked before installation.
# =============================================================================

log() { echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*"; }

SCRIPTS_DIR="$(cd "$(dirname "$0")" && pwd)"
FGBIO_ENV_FILE="$SCRIPTS_DIR/fgbio_env.sh"

FGBIO_VERSION="2.3.0"
FGBIO_JAR_PATH="$HOME/tools/fgbio/fgbio-${FGBIO_VERSION}.jar"

# ---------------------------------------------------------------------------
# Locate active conda environment — must be ctdna2
# ---------------------------------------------------------------------------
if [[ -z "${CONDA_PREFIX:-}" ]]; then
  echo "ERROR: No conda environment active. Activate ctdna2 first:" >&2
  echo "  conda activate ctdna2" >&2
  exit 1
fi

CONDA_ENV_NAME="$(basename "$CONDA_PREFIX")"
if [[ "$CONDA_ENV_NAME" != "ctdna2" ]]; then
  log "WARNING: Active conda environment is '$CONDA_ENV_NAME', not 'ctdna2'."
  log "Proceeding — installing into $CONDA_PREFIX"
fi

# ---------------------------------------------------------------------------
# Locate or download fgbio JAR (2.3.0)
#
# bioconda only packages fgbio 1.4.0 which lacks ZipperBams and current
# GroupReadsByUmi flags. We use the upstream release JAR instead.
# 01_setup_env.sh downloads this on first run; this script checks and
# re-downloads if absent (e.g. running 11 standalone on a fresh machine).
# The conda wrapper (if any) is NOT used — it prevents passing -Xmx.
# ---------------------------------------------------------------------------
if [[ -f "$FGBIO_JAR_PATH" ]]; then
  log "fgbio JAR already present: $FGBIO_JAR_PATH — skipping download."
else
  log "Downloading fgbio ${FGBIO_VERSION} JAR..."
  mkdir -p "$(dirname "$FGBIO_JAR_PATH")"
  wget -q -O "$FGBIO_JAR_PATH" \
    "https://github.com/fulcrumgenomics/fgbio/releases/download/${FGBIO_VERSION}/fgbio-${FGBIO_VERSION}.jar"
  log "Downloaded: $FGBIO_JAR_PATH"
fi

# ---------------------------------------------------------------------------
# Verify fgbio JAR works
# ---------------------------------------------------------------------------
log "Verifying fgbio JAR..."
java -Xmx512m -jar "$FGBIO_JAR_PATH" --version 2>&1 | grep -q "Version:" \
  || { echo "ERROR: fgbio JAR did not print expected version string: $FGBIO_JAR_PATH" >&2; exit 1; }
log "fgbio JAR verified."

# ---------------------------------------------------------------------------
# Write JAR path to fgbio_env.sh — sourced by 14_align_arms_cd.sh
# ---------------------------------------------------------------------------
cat > "$FGBIO_ENV_FILE" <<EOF
# Auto-generated by 11_install_missing_tools.sh — do not edit manually.
# Sources the fgbio JAR path for use in 14_align_arms_cd.sh.
export FGBIO_JAR="${FGBIO_JAR_PATH}"
EOF

log "Wrote FGBIO_JAR to $FGBIO_ENV_FILE"

# ---------------------------------------------------------------------------
# Install LoFreq
# ---------------------------------------------------------------------------
if command -v lofreq >/dev/null 2>&1; then
  LOFREQ_VERSION="$(lofreq version 2>&1 | head -1 || true)"
  log "LoFreq already installed: $LOFREQ_VERSION — skipping."
else
  log "Installing LoFreq via bioconda..."
  conda install -y -c bioconda -c conda-forge lofreq
  log "LoFreq installed."
fi

# ---------------------------------------------------------------------------
# Verify LoFreq works
# ---------------------------------------------------------------------------
log "Verifying LoFreq..."
lofreq version >/dev/null 2>&1 \
  || { echo "ERROR: lofreq command failed after installation" >&2; exit 1; }
log "LoFreq verified."

log "Script 11 complete."
log "  FGBIO_JAR=$FGBIO_JAR_PATH"
log "  fgbio_env.sh written to: $FGBIO_ENV_FILE"
log "  LoFreq: $(lofreq version 2>&1 | head -1)"
