#!/usr/bin/env bash
set -euo pipefail
source "$(dirname "$0")/00_config.sh"

# =============================================================================
# Install fgbio and LoFreq into the ctdna2 conda environment.
#
# fgbio: Fulcrum Genomics toolkit for UMI/consensus calling (bioconda).
#   Installed as a conda package — provides both a wrapper script and a JAR.
#   The JAR path is written to scripts/fgbio_env.sh so that 14_align_arms_cd.sh
#   can source it and invoke fgbio directly via `java -jar $FGBIO_JAR`.
#   Wrapper scripts suppress JVM memory flags, so we prefer the JAR directly.
#
# LoFreq: Low-frequency variant caller using Poisson model (bioconda).
#   Particularly sensitive at low VAF because it explicitly models per-base
#   error rates from quality scores — more principled than Mutect2 at VAF < 1%.
#   Used in Arm A and Arm C for tumor-only calling.
#
# This script is idempotent: each tool is checked before installation.
# =============================================================================

log() { echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*"; }

SCRIPTS_DIR="$(cd "$(dirname "$0")" && pwd)"
FGBIO_ENV_FILE="$SCRIPTS_DIR/fgbio_env.sh"

# ---------------------------------------------------------------------------
# Locate active conda environment — must be ctdna2
# ---------------------------------------------------------------------------
if [[ -z "${CONDA_PREFIX:-}" ]]; then
  echo "ERROR: No conda environment active. Activate ctdna2 first:" >&2
  echo "  conda activate ctdna2" >&2
  exit 1
fi

CONDA_ENV_NAME="$(basename "$CONDA_PREFIX")"
if [[ "$CONDA_ENV_NAME" != "ctdna2" ]]; then
  log "WARNING: Active conda environment is '$CONDA_ENV_NAME', not 'ctdna2'."
  log "Proceeding — installing into $CONDA_PREFIX"
fi

# ---------------------------------------------------------------------------
# Install fgbio
# ---------------------------------------------------------------------------
if command -v fgbio >/dev/null 2>&1; then
  FGBIO_VERSION="$(fgbio --version 2>&1 | head -1 || true)"
  log "fgbio already installed: $FGBIO_VERSION — skipping."
else
  log "Installing fgbio via bioconda..."
  conda install -y -c bioconda -c conda-forge fgbio
  log "fgbio installed."
fi

# ---------------------------------------------------------------------------
# Locate the fgbio JAR
#
# The bioconda fgbio package installs a versioned JAR under
# $CONDA_PREFIX/share/fgbio-*/fgbio-*.jar.  We search for it and take the
# most recent if multiple versions exist.  The wrapper at $CONDA_PREFIX/bin/fgbio
# is NOT used for pipeline steps because it prevents passing -Xmx.
# ---------------------------------------------------------------------------
log "Locating fgbio JAR..."
FGBIO_JAR_PATH="$(find "$CONDA_PREFIX/share" -name "fgbio-*.jar" 2>/dev/null \
  | grep -v '\-javadoc' | sort -V | tail -1 || true)"

if [[ -z "$FGBIO_JAR_PATH" ]]; then
  # Fallback: some bioconda builds use a non-versioned name
  FGBIO_JAR_PATH="$(find "$CONDA_PREFIX/share" -name "fgbio.jar" 2>/dev/null \
    | tail -1 || true)"
fi

if [[ -z "$FGBIO_JAR_PATH" ]]; then
  echo "ERROR: fgbio JAR not found under $CONDA_PREFIX/share" >&2
  echo "Try: find \$CONDA_PREFIX -name '*.jar' | grep -i fgbio" >&2
  exit 1
fi

log "fgbio JAR: $FGBIO_JAR_PATH"

# ---------------------------------------------------------------------------
# Verify fgbio JAR works
# ---------------------------------------------------------------------------
log "Verifying fgbio JAR..."
java -Xmx512m -jar "$FGBIO_JAR_PATH" --version >/dev/null 2>&1 \
  || { echo "ERROR: fgbio JAR failed to execute: $FGBIO_JAR_PATH" >&2; exit 1; }
log "fgbio JAR verified."

# ---------------------------------------------------------------------------
# Write JAR path to fgbio_env.sh — sourced by 14_align_arms_cd.sh
# ---------------------------------------------------------------------------
cat > "$FGBIO_ENV_FILE" <<EOF
# Auto-generated by 11_install_missing_tools.sh — do not edit manually.
# Sources the fgbio JAR path for use in 14_align_arms_cd.sh.
export FGBIO_JAR="${FGBIO_JAR_PATH}"
EOF

log "Wrote FGBIO_JAR to $FGBIO_ENV_FILE"

# ---------------------------------------------------------------------------
# Install LoFreq
# ---------------------------------------------------------------------------
if command -v lofreq >/dev/null 2>&1; then
  LOFREQ_VERSION="$(lofreq version 2>&1 | head -1 || true)"
  log "LoFreq already installed: $LOFREQ_VERSION — skipping."
else
  log "Installing LoFreq via bioconda..."
  conda install -y -c bioconda -c conda-forge lofreq
  log "LoFreq installed."
fi

# ---------------------------------------------------------------------------
# Verify LoFreq works
# ---------------------------------------------------------------------------
log "Verifying LoFreq..."
lofreq version >/dev/null 2>&1 \
  || { echo "ERROR: lofreq command failed after installation" >&2; exit 1; }
log "LoFreq verified."

log "Script 11 complete."
log "  FGBIO_JAR=$FGBIO_JAR_PATH"
log "  fgbio_env.sh written to: $FGBIO_ENV_FILE"
log "  LoFreq: $(lofreq version 2>&1 | head -1)"
